-- =========================================================
-- 01 - DATA MODEL: tabelle principali + indici
-- Schema: staging_paas
-- =========================================================

-- Tabella LOV (configurazione liste)
CREATE TABLE staging_paas.uat_lov (
  lov_type     VARCHAR2(30)  NOT NULL,
  lov_code     VARCHAR2(50)  NOT NULL,
  lov_label    VARCHAR2(200) NOT NULL,
  sort_order   NUMBER        DEFAULT 10,
  enabled_yn   CHAR(1)       DEFAULT 'Y' CHECK (enabled_yn IN ('Y','N')),
  CONSTRAINT pk_uat_lov PRIMARY KEY (lov_type, lov_code)
);

-- Tabella Use Case (owner per re-test)
CREATE TABLE staging_paas.uat_use_case (
  use_case_code   VARCHAR2(50)  PRIMARY KEY,
  use_case_title  VARCHAR2(200) NOT NULL,
  domain_stream   VARCHAR2(100) NOT NULL,
  owner_user_name VARCHAR2(128) NOT NULL,
  owner_email     VARCHAR2(256) NOT NULL,
  enabled_yn      CHAR(1)       DEFAULT 'Y' CHECK (enabled_yn IN ('Y','N')),
  created_on      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by      VARCHAR2(128) NOT NULL,
  updated_on      TIMESTAMP,
  updated_by      VARCHAR2(128)
);

CREATE INDEX staging_paas.idx_uat_use_case_stream ON staging_paas.uat_use_case(domain_stream);
CREATE INDEX staging_paas.idx_uat_use_case_owner  ON staging_paas.uat_use_case(owner_user_name);

-- Tabella principale: UAT_ISSUE
CREATE TABLE staging_paas.uat_issue (
  issue_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- audit
  created_on          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  created_by          VARCHAR2(128) NOT NULL,
  updated_on          TIMESTAMP,
  updated_by          VARCHAR2(128),
  -- contesto comune
  solution_type       VARCHAR2(10)  NOT NULL,
  application_module  VARCHAR2(100) NOT NULL,
  environment         VARCHAR2(50)  NOT NULL,
  domain_stream       VARCHAR2(100) NOT NULL,
  use_case_code       VARCHAR2(50),
  page_url            VARCHAR2(1000),
  tenant_pod          VARCHAR2(100),
  app_version         VARCHAR2(60),
  test_case_id        VARCHAR2(80),
  uat_step_ref        VARCHAR2(200),
  -- classificazione
  record_type         VARCHAR2(20)  NOT NULL,
  severity            VARCHAR2(10)  NOT NULL,
  priority            VARCHAR2(5),
  frequency           VARCHAR2(20),
  impact_flags        VARCHAR2(200),
  -- descrizioni
  title               VARCHAR2(120) NOT NULL,
  expected_behavior   CLOB          NOT NULL,
  actual_behavior     CLOB          NOT NULL,
  error_message       CLOB,
  prerequisites       CLOB,
  steps_to_reproduce  CLOB          NOT NULL,
  reproducible_yn     CHAR(1)       DEFAULT 'Y' CHECK (reproducible_yn IN ('Y','N')),
  notes               CLOB,
  -- gestione
  status              VARCHAR2(30)  NOT NULL,
  component           VARCHAR2(30),
  assignee            VARCHAR2(128),
  target_release      VARCHAR2(60),
  duplicate_of        NUMBER,
  -- proposta soluzione / retest / chiusura
  resolution_notes    CLOB,
  fix_version         VARCHAR2(60),
  fix_environment     VARCHAR2(50),
  retest_assigned_to  VARCHAR2(128),
  retest_instructions CLOB,
  retest_outcome      VARCHAR2(10),
  retest_notes        CLOB,
  resolved_on         TIMESTAMP,
  resolved_by         VARCHAR2(128),
  closure_reason      VARCHAR2(50),
  closure_evidence_link VARCHAR2(1000),
  closed_on           TIMESTAMP,
  closed_by           VARCHAR2(128),
  -- contesto estendibile
  context_payload     CLOB,
  CONSTRAINT fk_uat_issue_duplicate
    FOREIGN KEY (duplicate_of) REFERENCES staging_paas.uat_issue(issue_id),
  CONSTRAINT fk_uat_issue_use_case
    FOREIGN KEY (use_case_code) REFERENCES staging_paas.uat_use_case(use_case_code)
);

CREATE INDEX staging_paas.idx_uat_issue_status     ON staging_paas.uat_issue(status);
CREATE INDEX staging_paas.idx_uat_issue_severity   ON staging_paas.uat_issue(severity);
CREATE INDEX staging_paas.idx_uat_issue_stream     ON staging_paas.uat_issue(domain_stream);
CREATE INDEX staging_paas.idx_uat_issue_env        ON staging_paas.uat_issue(environment);
CREATE INDEX staging_paas.idx_uat_issue_assignee   ON staging_paas.uat_issue(assignee);
CREATE INDEX staging_paas.idx_uat_issue_created_on ON staging_paas.uat_issue(created_on);
CREATE INDEX staging_paas.idx_uat_issue_usecase    ON staging_paas.uat_issue(use_case_code);

-- Allegati
CREATE TABLE staging_paas.uat_issue_attachment (
  attachment_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id       NUMBER        NOT NULL,
  file_name      VARCHAR2(255) NOT NULL,
  mime_type      VARCHAR2(100),
  file_size      NUMBER,
  file_content   BLOB,
  description    VARCHAR2(500),
  uploaded_on    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  uploaded_by    VARCHAR2(128) NOT NULL,
  CONSTRAINT fk_uat_attach_issue
    FOREIGN KEY (issue_id) REFERENCES staging_paas.uat_issue(issue_id) ON DELETE CASCADE
);

CREATE INDEX staging_paas.idx_uat_attach_issue ON staging_paas.uat_issue_attachment(issue_id);

-- Commenti
CREATE TABLE staging_paas.uat_issue_comment (
  comment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id     NUMBER        NOT NULL,
  comment_text CLOB          NOT NULL,
  visibility   VARCHAR2(10)  DEFAULT 'PUBLIC' CHECK (visibility IN ('PUBLIC','INTERNAL')),
  comment_on   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  comment_by   VARCHAR2(128) NOT NULL,
  CONSTRAINT fk_uat_comment_issue
    FOREIGN KEY (issue_id) REFERENCES staging_paas.uat_issue(issue_id) ON DELETE CASCADE
);

CREATE INDEX staging_paas.idx_uat_comment_issue ON staging_paas.uat_issue_comment(issue_id);

-- Storico stati (audit workflow)
CREATE TABLE staging_paas.uat_issue_status_hist (
  hist_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id     NUMBER        NOT NULL,
  old_status   VARCHAR2(30),
  new_status   VARCHAR2(30)  NOT NULL,
  changed_on   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  changed_by   VARCHAR2(128) NOT NULL,
  change_note  VARCHAR2(500),
  CONSTRAINT fk_uat_hist_issue
    FOREIGN KEY (issue_id) REFERENCES staging_paas.uat_issue(issue_id) ON DELETE CASCADE
);

CREATE INDEX staging_paas.idx_uat_hist_issue      ON staging_paas.uat_issue_status_hist(issue_id);
CREATE INDEX staging_paas.idx_uat_hist_changed_on ON staging_paas.uat_issue_status_hist(changed_on);

-- Email outbox (fallback se APEX_MAIL non configurato)
CREATE TABLE staging_paas.uat_email_outbox (
  email_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_on TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  status     VARCHAR2(20)  DEFAULT 'PENDING',
  to_email   VARCHAR2(256) NOT NULL,
  cc_email   VARCHAR2(512),
  subject    VARCHAR2(300) NOT NULL,
  body_html  CLOB,
  body_text  CLOB,
  last_error VARCHAR2(1000)
);

CREATE INDEX staging_paas.idx_uat_email_outbox_status ON staging_paas.uat_email_outbox(status);
